home/urls.py
from django.urls import path, include
from django.contrib import admin
from home import views

app_name = 'home'

urlpatterns = [
    path('admin/', admin.site.urls),

    path('index/', views.index, name='index'),

    path('login/', views.login, name='login'),
    path('join/', views.join, name='join'),
    path('logout/', views.logout, name='logout'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

# for ckeditor
from django.conf import settings
from django.conf.urls.static import static

from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),

    path('home/', include('home.urls', namespace='home')),

    path('ckeditor/', include('ckeditor_uploader.urls')),         # for ckeditor

    path('stock/', include('stock.urls', namespace='stock')),

]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stock/urls.py
from django.urls import path, include
from django.contrib import admin
from stock import views

app_name = 'stock'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('stockhome/', views.stockhome, name='stockhome'),
    path('stockmodel/', views.stockmodel, name='stockmodel'),
    path('stocktrade/', views.stocktrade, name='stocktrade'),

]

stock/models.py
from django.db import models

# Create your models here.

stock/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import pickle
from sklearn.preprocessing import StandardScaler

import os
import json
import re
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM

from stock.myModule.envs import TradingEnv
from stock.myModule.envs_multi import TradingEnv_multi
from stock.myModule.agent import DQNAgent
from stock.myModule.agent_multi import DQNAgent_multi

from datetime import datetime, date

import time

from tensorflow.keras.models import load_model

# selenium을 통해 웹브라우저 접근시
from selenium import webdriver
import requests

# BeautifulSoup4 운용
from bs4 import BeautifulSoup

# 파일 복사
import shutil

# stock 리스트(시작)
def stockhome(request):

    return render(request, 'stock/stockhome.html')


#########################################  단일 종목 주가 예측 ## ###################################################
##### 단일 종목에 대한 주가 예측모델(LSTM) + 매매추천 : Q-Learning(강화학습),  Standardizati  #######################
#####################################################################################################################

def stockmodel(request):

    if request.method == "POST":

        ##################################   Mystock (주가 예측)  ##############################################
        # 기계 [Tensorflow] LSTM RNN을 이용하여 아마존 주가 예측하기
        # 학습을 통한 하나의 주식에 대한 다음날 주식 예측  +  qlearn(강화학습)을 통해 자동 주식 매매

        # 하이퍼파라미터
        seq_length = 28  # 1개 시퀀스의 길이(시계열데이터 입력 개수: 학습을 위한 데이터 갯수 0~28일 => 29번째 날를 위한 시퀀스)

        # 입력 파일 지정하기
        item = request.POST["item"]
        trade = request.POST.get("trade")
        option = request.POST.get("option")
        update = request.POST.get("update")

        # 준비: 디렉토리 생성
        # maybe_make_dir('stock/refStage/weights')
        # maybe_make_dir('stock/refStage/portfolio')

        downloadfile = "C:/Users/USER/Downloads/" + item + ".csv"
        stock_file_name = "C:/Users/USER/PycharmProjects/futureworld/stock/refStage/stock/" + item + ".csv"

        # 준비: 날짜 reference : The strftime() : datetime 데이터를 문자열로 전환 :  method returns a string representing date and time using date, time or datetime object.
        # now = datetime.now()                                    # current date and time
        # timestamp = now.strftime('%Y%m%d%H%M')                  # datatime을 문자열로 전환

        ##################################### 1. 옵션 : 최신 주식 데이터 업데이트   #############################
        if update == "update":

            # 기존 파일 제거
            if os.path.exists(downloadfile):
                os.remove(downloadfile)
            if os.path.exists(stock_file_name):
                os.remove(stock_file_name)

            # base_date = datetime(2015, 1, 1).date()
            my_string = "2015-01-01"
            start_day = 1420070400            # 2015.1.1 기준
            base_date = datetime.strptime(my_string, "%Y-%m-%d")
            base_date = base_date.date()
            print("base_date:", base_date)

            today = datetime.now().date()
            print("today:", today)

            # Difference between two dates
            n_date = today - base_date
            print("날짜 기간:", n_date.days)

            ref_1=start_day+n_date.days*86400
            print(ref_1)


            browser = webdriver.Chrome("C:/Users/USER/PycharmProjects/futureworld/static/resource/chromedriver.exe")
            browser.implicitly_wait(3)

            url="https://finance.yahoo.com/quote/"+item+"/history?period1="+str(start_day)+"&period2="+str(ref_1)+"&interval=1d&filter=history&frequency=1d"
            browser.get(url)
            print(url)

            download = browser.find_element_by_css_selector('#Col1-1-HistoricalDataTable-Proxy section div:nth-child(1) div:nth-child(2) span:nth-child(2) a')
            download.click()

            time.sleep(15)                              # 5초 대기

            browser.quit()

            redirect('stock/stockmodel.html')


        ####### 2. 주식 데이터 분석(정규화, X-train, Y-train 추출)

        ## 파일 복사
        shutil.copyfile(downloadfile, stock_file_name)

        encoding = 'euc-kr'                                                                         # 문자 인코딩
        names = ['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume']

        ################## csv 파일을 pandas dataframe으로 불러들임
        raw_dataframe = pd.read_csv(stock_file_name, names=names, encoding=encoding)                # Pandas 이용 csv파일 로딩(dataframe)

        raw_dataframe.info()                                                                        # 데이터 정보 출력

        ## dataframe에서 데이터 불필요 부분 정리
        del raw_dataframe['Date']                           # axis=1 세로 column축 date 열 시간열을 제거(dataframe 재생성하지 않음)
        # raw_dataframe.drop('Date', axis=1, inplace=True)

        print("raw_dataframe-type:", type(raw_dataframe))

        ######################################## ndarray로 데이터 변환(dataframe => nparray) 데이터 형태 변환
        stock_info = raw_dataframe.values[1:]            # (1259,6) 금액&거래량 문자열을 부동소수점형으로 변환한다(0줄 레벨 제외)
        print("stock_info:", type(stock_info))

        stock_info = stock_info.astype(np.float)      #  => 정수를 실수형으로 전환

        # 데이터 정규화 : 가격과 거래량 수치의 차이가 많아나서 각각 별도로 정규화한다
        price = stock_info[:, :-1]                              # (1259, 5),  volumn(마지막 열) 제외한 데이터
        norm_price = min_max_scaling(price)                     # 가격형태 데이터 정규화 처리(5개 열)

        # 거래량형태 데이터를 정규화한다
        # ['Open','High','Low','Close','Adj Close','Volume']에서 마지막 'Volume'만 취함
        # [:,-1]이 아닌 [:,-1:]이므로 주의하자! 스칼라가 아닌 벡터값 산출해야만 쉽게 병합 가능(차원 통일 해야)

        volume = stock_info[:, -1:]                             # (1259, 1)   volumn 데이터만 가져옴(1개 열)
        norm_volume = min_max_scaling(volume)                   # 거래량형태 데이터 정규화 처리

        ## 새로운 데이터(dafaframe) 생성 :  행은 그대로 두고 열을 우측에 붙여 합친다  axis 0(동일한 컬럼),1(상이한 컬럼)
        ## axis : {0/’index’, 1/’columns’}, default 0


        stock_data = np.concatenate((norm_price, norm_volume), axis=1)          # (1259, 6) : column을 합친다(1259,5) +(1259,1)
        # stock_data = pd.concat([norm_price, norm_volume], axis=1)             # pasdas numpy 차이

        print("stock_data.shape", stock_data.shape)
        # stock_data = np.around(stock_data)                          # (1259, 6)

        cPrice = stock_data[:, [-3]]                            # (1268,1) 정규화된 주식종가(close행 -3)이다
        closePrice = stock_info[:, [-3]]                        # (1268,1) 아래 Qlearning을 위함 비정규화된 주식 종가 (close행 -3)이다

        dataX = []                                              # 리스트 입력으로 사용될 Sequence Data
        dataY = []                                              # 리스트 출력(타켓)으로 사용

        for i in range(0, len(stock_data) - seq_length):
            _x = stock_data[i: i + seq_length]                  # [ [ 0:28] [1:29].......[?~?+28]
            _y = cPrice[i + seq_length]                         # 다음 나타날 주가(정답)  cPrice[28], cPrice[29].....cPrice[?+28]

            dataX.append(_x)                                    # 리스트 (1231, 28, 6) dataX 리스트에 추가 => 3차원 리스트 생성
            dataY.append(_y)                                    # 리스트 (1231, 1) dataY 리스트에 추가

        print("dataX.shape", np.array(dataX).shape)
        print("dataY.shape", np.array(dataY).shape)

        # 학습용/테스트용 데이터 생성(전체 90%를 학습용 데이터로 사용, 나머지(10%)를 테스트용 데이터로 사용)
        train_size = int(len(dataY) * 0.9)
        test_size = len(dataY) - train_size

        # 데이터를 잘라 학습용 데이터,  테스트용 데이터 생성(리스트를 nparray로 생성)
        x_train = np.array(dataX[0:train_size])                 # (1168, 28, 6)
        y_train = np.array(dataY[0:train_size])                 # (1168, 1)
        x_test = np.array(dataX[train_size:len(dataX)])         # (125, 28, 6)
        y_test = np.array(dataY[train_size:len(dataY)])         # (125, 1)



        ######### 3. 주가 예측 모델
        start_time = datetime.now()                     # 시작시간을 기록한다
        print('학습을 시작합니다...')

        ## model 이용하는 경우(LSTM방식 이용)
        input_data_column_cnt = 6  # 입력데이터의 컬럼 개수(Variable 개수)
        output_data_column_cnt = 1  # 결과데이터의 컬럼 개수
        epoch_num = 100  # 에폭 횟수(학습용 전체데이터를 몇 회 반복해서 학습할 것인가 입력)
        batch_size_num = 100

        model_file = "stock/refStage/weights/" + item + "_predict.h5"

        #######  주식 예측 모델이 존재 여부
        if not os.path.exists(model_file):

            model = Sequential()
            model.add(LSTM(seq_length, return_sequences=True, input_shape=(seq_length, input_data_column_cnt)))     # 28개 유닉스 지정하고 입력값은 (28,6)개
            model.add(LSTM(64, return_sequences=False))                                                             # 64개 유닉스 지정(조정해서 최적치 구할수)
            model.add(Dense(output_data_column_cnt, activation='linear'))                                           # 1개의 결과 산출
            model.compile(loss='mse', optimizer='rmsprop')

            # 모델 상태 보기
            model.summary()

            # 모델 학습하기
            model.fit(x_train, y_train, validation_data=(x_test, y_test), batch_size=batch_size_num, epochs=epoch_num)

            end_time = datetime.now()                               # 종료시간을 기록한다
            elapsed_time = end_time - start_time                    # 경과시간을 구한다
            print('elapsed_time per epoch:', elapsed_time / epoch_num)

            ## 주가 예상가격 모델 가중치 저장
            model.save('stock/refStage/weights/'+ item + '_predict.h5')

        else:

            model = load_model(model_file)


        ###################  주가 가격 예상(TensorFlow 플레이스 홀더 확인)

        # sequence length만큼의 가장 최근 데이터를 슬라이싱한다

        recent_data = np.array([stock_data[len(stock_data) - seq_length:]])        #(1, 28, 6)    (1258,6)에서 마지막 28일간의 주식데이터를 추출
        print("recent_data.shape", recent_data.shape)

        # 내일 종가 예측
        next_predict = model.predict(recent_data)           # (1,1) : recent_data(1, 28, 6) 최근 28일 데이터의 예상치는 하나의 가격[ [ ] ]

        # 금액데이터를 역정규화

stock/templates/stock/stockhome.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style type="text/css">

#body_index{
	background-image:url("{% static '/image/main/city_night.jpg' %}");
}
img {
  display: block;
  max-width:230px;
  max-height:95px;
  width: auto;
  height: auto;
}
/* @media screen and (max-width:768px){
  .card-body{max-height:2em; padding:0;align:center;}
  .card-title{margin:0;align:center;font-size: 0.3em; }
} */
</style>

<div id="body_index" class="m-3 p-5">

    <!-- main content -->
    <div class="row col-md-10 offset-md-1 d-flex justify-content-around">

		<dd class="col-4 mb-4" style="display:none;">
			<div class="card"   >
	    		<a href="{% url 'stock:stockmodel' %}"><img class="card-img-top img-fluid rounded" src="{% static 'image/green/green_6.jpg' %}" alt="Card image" style="width:100%"></a>
	    		<div class="card-body p-1 d-flex justify-content-center">
	      			<a href="{% url 'stock:stockmodel' %}"><h6 class="card-title" style="font-size:3vw">Prediction</h6></a>
	    		</div>
	  		</div>
		</dd>

		<dd class="col-4 mb-4" style="display:none;">
			<div class="card"   >
	    		<a href="{% url 'stock:stockhome' %}"><img class="card-img-top img-fluid rounded" src="{% static 'image/green/green_6.jpg' %}" alt="Card image" style="width:100%"></a>
	    		<div class="card-body p-1 d-flex justify-content-center">
	      			<a href="{% url 'stock:stockhome' %}"><h6 class="card-title" style="font-size:3vw">AutoTrade</h6></a>
	    		</div>
	  		</div>
		</dd>



		<div class="text-center">
			<input type="button" class="btn btn-success" value="돌아가기" onclick="history.back(); return false ;" />
		</div>
	</div>
	<input type="button" id="loadMore" class="btn btn-success" value="더보기" />

  	<p class="totop"><a href="#top">Back to top</a></p>

</div>
{% endblock %}

{% block js %}
<script type="text/javascript">

<!--첫화면 에니메이션 처리-->
$(function(){

    $("dd").slice(0, 9).show(); 					// select the first 9

    $("#loadMore").click(function(e){ 				// click event for load more
        e.preventDefault();
        $("dd:hidden").slice(0, 3).show(); 			// select next 3 hidden divs and show them
        if($("div:hidden").length == 0){ 			// check if any hidden divs still exist
        	$("#loadMore").fadeOut('slow');
            	//alert("No more divs"); 			// alert if there are none left
        	}
        $('html,body').animate({
            scrollTop: $(this).offset().top
        }, 1500);
    });
});

</script>
<script src="{% static 'js/more_load.js' %}"></script>

{% endblock %}

stock/templates/stock/stockmodel.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
#Home{
	background-image:url("{% static '/image/main/noisy_blue.jpg' %}");
}
span {
    border-radius: 10px; background-color: #ffe0e0; padding:8px;
}

</style>

<div id="Home" class="col-11 p-4 m-4">
<form name="form_option">

    {% csrf_token %}

    <h5> 주가 예측 </h5><br/>
    <h6> 예) https://finance.yahoo.com/quote/IBM/history?p=IBM  에서 5년간 주가 데이터를 DeepFrame/refStage/stock/ibm.csv 파일로 저장 </h6><br/>

    <h5> 종목 선택? </h5><br/>
    <div class="form-check-inline">
        <label class="form-check-label">
            <input type="radio" class="form-check-input" name="item" value="ibm">IBM
        </label>
    </div>
    <div class="form-check-inline">
        <label class="form-check-label">
            <input type="radio" class="form-check-input" name="item" value="msft">MSFT
        </label>
    </div>
    <div class="form-check-inline">
        <label class="form-check-label">
            <input type="radio" class="form-check-input" name="item" value="nvda">NVIDA
        </label>
    </div>
    <div class="form-check-inline">
        <label class="form-check-label">
            <input type="radio" class="form-check-input" name="item" value="googl">Google
        </label>
    </div>
    <div class="form-check-inline">
        <label class="form-check-label">
            <input type="radio" class="form-check-input" name="item" value="005930.KS">Samsung
        </label>
    </div>
    <br/><br/>
    <div>=====================================================================</div>

    <h5> 옵션1: 최신 주가 업데이트?(deepstock/refStage/stock폴더에 "종목명.csv"로 저장) </h5><br/>
    <div class="form-check-inline">
        <label class="form-check-label">
            <input type="radio" class="form-check-input" name="update" value="update">최신주가 업데이트
        </label>
    </div>
    <div class="form-check-inline">
        <label class="form-check-label">
            <input type="radio" class="form-check-input" name="update" value="2"> 기타 옵션
        </label>
    </div>
    <br/><br/><br/>

    <h5> 옵션 #2: 그래프? 관련 뉴스? </h5><br/>
    <div class="form-check-inline">
        <label class="form-check-label">
            <input type="radio" class="form-check-input" name="option" value="plot">예상주가비교
        </label>
    </div>
    <div class="form-check-inline">
        <label class="form-check-label">
            <input type="radio" class="form-check-input" name="option" value="news"> 관련 뉴스
        </label>
    </div>
    <br/>
    <br/><br/>

    <h5> 옵션 #3: 자동매매 학습 or 매매 추천</h5><br/>

    <div class="form-check-inline">
        <label class="form-check-label">
            <input type="radio" class="form-check-input" name="trade" value="train">자동매매 학습
        </label>
    </div>
    <div class="form-check-inline">
        <label class="form-check-label">
            <!--<input type="radio" class="form-check-input" name="optradio3" value="action">매매추천-->
            <input type="radio" class="form-check-input" name="trade" value="action">매매추천
        </label>
    </div>
    <div class="form-check-inline">
        <label class="form-check-label">
            <input type="radio" class="form-check-input" name="trade" value="2">기타옵션
        </label>
    </div>
    <br/><br/>

    <div id="resp_1"></div><br/>
    <div id="resp_2"></div><br/>

    <input id="text_submit" type="button" value="Enter"/>

</form>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">

    <!--## 일반적인 form 형태(POST) 방식 전송-->

    $("#text_submit").on('click', function() {

        var frm = document.form_option;

        if(frm.item.value == ""){alert("Enter stock-item!");return false;}

        frm.action = "{% url 'stock:stockmodel' %}";
        frm.method = "POST";
        frm.submit();

    });

<!--    ## AJAX 형식으로 전송-->
<!--    $("#text_submit").on('click', function() {-->

<!--        var frm = document.form_option;-->

<!--        var item = frm.item.value;-->
<!--        var option = frm.option.value;-->
<!--        var trade = frm.trade.value;-->
<!--        var update = frm.update.value;-->
<!--        &lt;!&ndash;var weights = $('#weights').val();&ndash;&gt;-->

<!--        var url2 = "{% url 'stock:stockmodel' %}";-->

<!--        $.ajax({-->
<!--            type : "POST",-->
<!--            url : url2,-->
<!--            data : {-->
<!--                'item' : item,-->
<!--                'trade' : trade,-->
<!--                'option' : option,-->
<!--                'update' : update,-->
<!--                &lt;!&ndash;'weights' : weights,&ndash;&gt;-->
<!--                'csrfmiddlewaretoken': '{{ csrf_token }}',-->
<!--            },-->
<!--            success : function(resp){-->

<!--                &lt;!&ndash;json 타입의 respe데이터를 dictionary 타입으로 parse JQuery&ndash;&gt;-->
<!--                var resp = jQuery.parseJSON(resp);-->

<!--                var html_1 = "<div><span> 최종일 주가 : " + resp.resp0 +-->
<!--                    "</span></br></br><span> 내일 예상 주가 : " + resp.resp1 +-->
<!--                    "(" + resp.rate +-->
<!--                    "%)</span></br></br><span> 매매 추천 : " + resp.action +-->
<!--                    "</div>";-->

<!--                $("#resp_1").html(html_1);-->

<!--&lt;!&ndash;                var article_str = new String(resp.article_list);&ndash;&gt;-->
<!--&lt;!&ndash;                var href_str = new String(resp.href_list);&ndash;&gt;-->
<!--&lt;!&ndash;                var article_list = article_str.split(',');&ndash;&gt;-->
<!--&lt;!&ndash;                var href_list = href_str.split(',');&ndash;&gt;-->

<!--&lt;!&ndash;                var html_news = "";&ndash;&gt;-->
<!--&lt;!&ndash;                for(var i in article_list){&ndash;&gt;-->
<!--&lt;!&ndash;                    var html_2 = "<div><a href=https://news.google.com" + href_list[i] + "</a>" + article_list[i] + "<br/><br/>";&ndash;&gt;-->
<!--&lt;!&ndash;                    var html_news = html_news + html_2;&ndash;&gt;-->
<!--&lt;!&ndash;                };&ndash;&gt;-->

<!--&lt;!&ndash;                $("#resp_2").html(html_news);&ndash;&gt;-->
<!--            }-->
<!--        });-->
<!--    });-->


</script>
{% endblock %}

stock/templates/stock/stockresult.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style>
#Home{
	background-image:url("{% static '/image/main/noisy_blue.jpg' %}");
}
span {
    border-radius: 10px; background-color: #ffe0e0; padding:8px;
}

</style>


<div id="Home" class="col-11 p-4 m-4">

    <h5>Mystock 일일 주가 예측 </h5><br/>

    <h5> 종목 :  {{item}} </h5><br/>

    <div>
        <span> 최종일 주가 : {{resp0}} </span><br/><br>
        <span> 내일 예상 주가 : {{resp1}} ( {{rate}} %)</span></br><br/>
        <span> 매매 추천 : {{action}} </span><br/><br/>
    </div></br><br/>

    {% if article_dict %}
    {{item}} 관련뉴스 <br/>
    {% for key, value in article_dict.items %}

    <div>
        <a href="https://news.google.com{{value}}">{{key}}</a><br/><br/>

    </div>
    {% endfor %}
    {% endif %}

    <div class="d-flex p-3">
        &nbsp;
  		<input class="btn btn-info p-2" value="이전 돌아가기" onclick="history.back(); return false;"/>&nbsp;&nbsp;
  		<a class="mx-auto btn btn-secondary" href="{% url 'stock:stockhome' %}" role="button">Stock</a>

    </div>

</div>

{% endblock %}

stock/templates/stock/stocktrade.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style>
#Home{
	background-image:url("{% static '/image/main/noisy_blue.jpg' %}");
}
span {
    border-radius: 10px; background-color: #ffe0e0; padding:8px;
}

</style>

<div id="Home" class="col-11 p-4 m-4">
<form name="form_option">

    <h5>Qlearn-trading 주식 자동 매매 </h5><br/>
    <h6> 예) https://finance.yahoo.com/quote/IBM/history?p=IBM  에서 5년간 주가 데이터를 DeepFrame/refStage/stock/ibm.csv 파일로 저장 </h6><br/>

    <h5> 보유 종목? </h5><br/>
    <div class="form-check-inline">
        <label class="form-check-label">
            <input type="checkbox" name = "stock" class="form-check-input" value="ibm">IBM
        </label>
    </div>
    <div class="form-check-inline">
        <label class="form-check-label">
            <input type="checkbox" name = "stock" class="form-check-input" value="googl">Google
        </label>
    </div>
    <div class="form-check-inline">
        <label class="form-check-label">
            <input type="checkbox" name = "stock" class="form-check-input" value="msft">MSFT
        </label>
    </div>
    <br/><br/>


    <div>====================================================================================</div>
    <h5> 옵션1: 최신 주가 업데이트?(deepstock/refStage/stock폴더에 "종목명.csv"로 저장) </h5><br/>
    <div class="form-check-inline">
        <label class="form-check-label">
            <input type="radio" class="form-check-input" name="optradio" value="update">최신주가 업데이트
        </label>
    </div>
    <div class="form-check-inline">
        <label class="form-check-label">
            <input type="radio" class="form-check-input" name="optradio" value="train">학습
        </label>
    </div>
    <div class="form-check-inline">
        <label class="form-check-label">
            <input type="radio" class="form-check-input" name="optradio" value="test">Test
        </label>
    </div>
    <br/><br/>

    <div id="resp"></div><br/>

    <input id="text-submit" type="button" value="Enter"/>

</form>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">


    $("#text-submit").on('click', function() {

        var frm = document.form_option;

        var items = new Array();

        $("input:checkbox:checked").each(function() {
           items.push($(this).val());
        });


        <!--array to String-->
        var items = items.toString();


        var option = frm.optradio.value;

        var url2 = "{% url 'stock:stocktrade' %}";


        $.ajax({
            type : "POST",
            url : url2,
            data : {
                'items' : items,
                'option' : option,
                'csrfmiddlewaretoken': '{{ csrf_token }}',
            },
            success : function(resp){

                <!--json 타입의 respe데이터를 dictionary 타입으로 parse JQuery-->
                <!--var resp = jQuery.parseJSON(resp);-->

                var html = "<div class='bot'><span> 매매 추천 : " + resp +
                    "</div>";

                $("#resp").html(html);
            }
        });

    });


</script>
{% endblock %}